services:
  intershop:
    build:
      context: ./intershop
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop_db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      PAYMENT_SERVICE_URL: http://payment-service:8082
      KEYCLOAK_CLIENT_SECRET: ${CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: intershop
      KEYCLOAK_ISSUE_URL: http://keycloak:8080/realms/master
    depends_on:
      - postgres
      - redis
      - keycloak
      - payment-service

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      KEYCLOAK_ISSUE_URL: http://keycloak:8080/realms/master
    depends_on:
      - keycloak

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: intershop_db
    ports:
      - "5430:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev