services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop_db
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: intershop_db
    ports:
      - "5430:5432"